openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: Authentication service for Startup Metrics Platform using Google OAuth and JWT tokens
  contact:
    name: Platform Support
    email: support@startup-metrics.com

servers:
  - url: /api/v1/auth
    description: Authentication service base path

paths:
  /google/login:
    get:
      summary: Initiate Google OAuth flow
      operationId: initiateGoogleAuth
      tags:
        - Authentication
      parameters:
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
            format: uri
          description: URI to redirect after successful authentication
      responses:
        '302':
          description: Redirect to Google consent screen
          headers:
            Location:
              schema:
                type: string
              description: Google OAuth consent URL
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /google/callback:
    get:
      summary: Handle Google OAuth callback
      operationId: handleGoogleCallback
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: OAuth authorization code
        - name: state
          in: query
          required: true
          schema:
            type: string
          description: CSRF state token
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              schema:
                type: string
              description: HTTP-only secure cookie with JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /refresh:
    post:
      summary: Refresh JWT token
      operationId: refreshToken
      tags:
        - Token Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid or expired token
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /logout:
    post:
      summary: User logout
      operationId: logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          headers:
            Clear-Cookie:
              schema:
                type: string
              description: Clear session cookie
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AuthResponse:
      type: object
      required:
        - token
        - user
      properties:
        token:
          type: string
          description: JWT access token
        user:
          type: object
          required:
            - id
            - email
            - name
            - role
            - permissions
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            name:
              type: string
            role:
              type: string
              enum: [ADMIN, ANALYST, USER, GUEST]
            permissions:
              type: object
              properties:
                canViewMetrics:
                  type: boolean
                canEditMetrics:
                  type: boolean
                canGenerateReports:
                  type: boolean
                canManageUsers:
                  type: boolean
                canConfigureSystem:
                  type: boolean
                canExportData:
                  type: boolean
                canAccessAuditLogs:
                  type: boolean

    TokenResponse:
      type: object
      required:
        - token
        - expiresIn
      properties:
        token:
          type: string
          description: New JWT access token
        expiresIn:
          type: integer
          description: Token expiration time in seconds
          example: 3600

    ErrorResponse:
      type: object
      required:
        - type
        - status
        - code
        - message
      properties:
        type:
          type: string
          format: uri
          description: A URI reference identifying the problem type
          example: https://api.startup-metrics.com/errors/auth/token-expired
        status:
          type: integer
          description: HTTP status code
          example: 401
        code:
          type: string
          description: Application-specific error code
          example: AUTH001
        message:
          type: string
          description: Human-readable error message
          example: OAuth token expired or invalid
        details:
          type: object
          description: Additional error context
        instance:
          type: string
          format: uri
          description: URI reference identifying the specific occurrence
          example: /api/v1/auth/refresh/12345

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token authentication

security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: OAuth and session management endpoints
  - name: Token Management
    description: JWT token operations