apiVersion: 1

datasources:
  # Prometheus data source for metrics collection
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: '15s'  # Matches Prometheus scrape_interval
      queryTimeout: '30s'
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  # Elasticsearch data source for centralized logging
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: startup-metrics-*
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeField: '@timestamp'
      esVersion: '7.9.0'
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      interval: Daily
      timeInterval: '1m'

  # Tempo data source for distributed tracing
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    version: 1
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        enabled: true
      lokiSearch:
        enabled: true
      serviceMap:
        enabled: true