apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-metrics-config
  namespace: startup-metrics
  labels:
    app: startup-metrics
    environment: production
data:
  # API Gateway Configuration
  API_GATEWAY_CONFIG: |
    {
      "PORT": "3000",
      "NODE_ENV": "production",
      "RATE_LIMIT_WINDOW_MS": "60000",
      "RATE_LIMIT_MAX_REQUESTS": "100",
      "RATE_LIMIT_BURST": "150",
      "CORS_ALLOWED_ORIGINS": "https://*.startup-metrics.com",
      "CORS_MAX_AGE": "86400",
      "METRICS_SERVICE_URL": "http://metrics-service:3002",
      "AUTH_SERVICE_URL": "http://auth-service:3001",
      "REPORT_SERVICE_URL": "http://report-service:3003",
      "REQUEST_TIMEOUT_MS": "5000",
      "COMPRESSION_ENABLED": "true"
    }

  # Authentication Service Configuration
  AUTH_SERVICE_CONFIG: |
    {
      "PORT": "3001",
      "NODE_ENV": "production",
      "SESSION_DURATION": "3600",
      "TOKEN_EXPIRY": "86400",
      "REFRESH_TOKEN_EXPIRY": "604800",
      "MAX_SESSIONS_PER_USER": "3",
      "GOOGLE_OAUTH_CALLBACK_URL": "https://api.startup-metrics.com/auth/google/callback",
      "REDIS_HOST": "redis-master",
      "REDIS_PORT": "6379",
      "REDIS_MAX_RETRIES": "3",
      "SESSION_CLEANUP_INTERVAL": "3600"
    }

  # Metrics Service Configuration
  METRICS_SERVICE_CONFIG: |
    {
      "PORT": "3002",
      "NODE_ENV": "production",
      "CACHE_TTL": "900",
      "CACHE_STALE_TTL": "1800",
      "BENCHMARK_UPDATE_INTERVAL": "3600",
      "CALCULATION_BATCH_SIZE": "1000",
      "MAX_CONCURRENT_CALCULATIONS": "50",
      "REDIS_HOST": "redis-master",
      "REDIS_PORT": "6379",
      "REDIS_MAX_RETRIES": "3",
      "DB_HOST": "postgres-master",
      "DB_PORT": "5432",
      "DB_NAME": "startup_metrics",
      "DB_POOL_MIN": "5",
      "DB_POOL_MAX": "20",
      "DB_IDLE_TIMEOUT": "10000"
    }

  # Report Service Configuration
  REPORT_SERVICE_CONFIG: |
    {
      "PORT": "3003",
      "NODE_ENV": "production",
      "REPORT_CACHE_TTL": "3600",
      "PDF_GENERATION_TIMEOUT": "30000",
      "MAX_CONCURRENT_REPORTS": "50",
      "MAX_REPORT_SIZE_MB": "10",
      "REPORT_CLEANUP_INTERVAL": "86400",
      "S3_BUCKET": "startup-metrics-reports",
      "S3_REGION": "us-east-1",
      "S3_ACL": "private",
      "S3_STORAGE_CLASS": "STANDARD",
      "REPORT_RETENTION_DAYS": "30"
    }