apiVersion: v1
kind: Secret
metadata:
  name: startup-metrics-secrets
  namespace: startup-metrics
  labels:
    app: startup-metrics
    environment: production
    managed-by: platform-team
    security-tier: high
  annotations:
    rotation-schedule: "90-days"
    last-rotated: "2024-01-01T00:00:00Z"  # Update with actual timestamp
    encryption: "aes-256-gcm"
    backup-enabled: "true"
type: Opaque
data:
  # Auth Service Secrets
  auth.jwt.private.key: ${JWT_PRIVATE_KEY}  # Base64 encoded RSA private key
  auth.jwt.public.key: ${JWT_PUBLIC_KEY}    # Base64 encoded RSA public key
  auth.google.client.id: ${GOOGLE_CLIENT_ID}
  auth.google.client.secret: ${GOOGLE_CLIENT_SECRET}
  auth.session.secret: ${SESSION_SECRET}
  auth.token.encryption.key: ${TOKEN_ENCRYPTION_KEY}
  auth.refresh.token.secret: ${REFRESH_TOKEN_SECRET}

  # Metrics Service Secrets
  metrics.db.user: ${DB_USER}
  metrics.db.password: ${DB_PASSWORD}
  metrics.db.encryption.key: ${DB_ENCRYPTION_KEY}
  metrics.redis.password: ${REDIS_PASSWORD}
  metrics.redis.tls.key: ${REDIS_TLS_KEY}
  metrics.encryption.key: ${METRICS_ENCRYPTION_KEY}
  metrics.backup.encryption.key: ${BACKUP_ENCRYPTION_KEY}

  # Report Service Secrets
  report.aws.access.key.id: ${AWS_ACCESS_KEY_ID}
  report.aws.secret.access.key: ${AWS_SECRET_ACCESS_KEY}
  report.storage.encryption.key: ${STORAGE_ENCRYPTION_KEY}
  report.signing.key: ${REPORT_SIGNING_KEY}
  report.pdf.encryption.key: ${PDF_ENCRYPTION_KEY}

---
# RBAC Role for accessing secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: startup-metrics-secrets-reader
  namespace: startup-metrics
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["startup-metrics-secrets"]
  verbs: ["get"]

---
# Role Bindings for service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-secrets-reader
  namespace: startup-metrics
subjects:
- kind: ServiceAccount
  name: auth-service
  namespace: startup-metrics
roleRef:
  kind: Role
  name: startup-metrics-secrets-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-service-secrets-reader
  namespace: startup-metrics
subjects:
- kind: ServiceAccount
  name: metrics-service
  namespace: startup-metrics
roleRef:
  kind: Role
  name: startup-metrics-secrets-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: report-service-secrets-reader
  namespace: startup-metrics
subjects:
- kind: ServiceAccount
  name: report-service
  namespace: startup-metrics
roleRef:
  kind: Role
  name: startup-metrics-secrets-reader
  apiGroup: rbac.authorization.k8s.io